feat: Add get list endpoint
decentraland/marketplace-favorites-server pull request #113
Opened 2023-05-12 17:19 UTC by kevinszuchet

Closes #102

2023-05-12 21:16 UTC, LautaroPetaccio commented on src/ports/lists/component.ts
> +    const list = await getList(listId, { userAddress })
If the `checkPermission` flag is set to `true` as default and the list has a view permission for all, the user will be able to add picks to the list. We might want to give the `getList` function the functionality to check for a specific condition. It must be also taken into account that EDIT > VIEW.

2023-05-12 21:16 UTC, LautaroPetaccio commented on src/ports/lists/component.ts
> +    }
```suggestion
      getListQuery.append(SQL`
        LEFT JOIN favorites.acl ON favorites.lists.id = favorites.acl.list_id
        WHERE 
      `)
    }
```

2023-05-12 21:21 UTC, LautaroPetaccio reviewed
Great job! I've left some comments to be reviewed.

2023-05-12 21:21 UTC, LautaroPetaccio commented on src/ports/lists/component.ts
> +          AND (favorites.acl.grantee = ${userAddress} OR favorites.acl.grantee = ${GRANTED_TO_ALL})
If we join the two tables using `favorites.lists.id = favorites.acl.list_id`, we can then leave the `(favorites.acl.grantee = ${userAddress} OR favorites.acl.grantee = ${GRANTED_TO_ALL})` condition to a where so the list doesn't get retrieved if it doesn't fulfill the requirements, falling into the `ListNotFoundError`.
This will also remove the need to check in the handler if the user has or not permissions. If the user doesn't have permissions we can return the `ListNotFoundError` so lists can't be discoverable.

2023-05-15 09:39 UTC, kevinszuchet commented on src/ports/lists/component.ts
> +    const list = await getList(listId, { userAddress })
Great catch, WDYT about the new alternative?

2023-05-15 09:42 UTC, kevinszuchet commented on src/ports/lists/component.ts
> +          AND (favorites.acl.grantee = ${userAddress} OR favorites.acl.grantee = ${GRANTED_TO_ALL})
If I understood correctly, by doing this, we would have a problem creating the access since the `createAccess` function validates that the list exists, and the validation would fail because of the `JOIN.`

Also, I'd prefer to show a 403 instead of a 404 if the lists exist, but the user doesn't have the permissions to interact with it. WDYT?

2023-05-15 19:30 UTC, LautaroPetaccio requested changes
I've left some comments to be reviewed. We need to fix a bit the permissions code and it will be set to go.

2023-05-15 19:30 UTC, LautaroPetaccio commented on src/ports/lists/component.ts
> +        WHERE (favorites.acl.grantee = ${userAddress} OR favorites.acl.grantee = ${GRANTED_TO_ALL}) AND favorites.acl.permission = ANY(${requiredPermissions}::text[])
If I'm not wrong, as we're using a `WHERE` now, if the list does not have an ACL or has one with a different permissions than the ones we've requested, it will return 0 rows thus falling into the condition at the line 73 which will throw the `ListNotFoundError`.

2023-05-15 19:30 UTC, LautaroPetaccio commented on test/unit/lists-component.spec.ts
> +    it('should have made the query to get without checking if the list belongs to the default user or if has the required permissions', async () => {
```suggestion
    it('should have made the query to get without checking if the list belongs to the default user or if has the required permissions', () => {
```

2023-05-15 19:30 UTC, LautaroPetaccio commented on test/unit/lists-component.spec.ts
> +    it('should have made the query to get the list checking if the list belongs to the default user without taking into account the permissions', async () => {
```suggestion
    it('should have made the query to get the list checking if the list belongs to the default user without taking into account the permissions', () => {
```

2023-05-15 19:30 UTC, LautaroPetaccio commented on test/unit/lists-component.spec.ts
> +      it('should have made the query to get the list matching those conditions', async () => {
```suggestion
      it('should have made the query to get the list matching those conditions', () => {
```

2023-05-15 19:30 UTC, LautaroPetaccio commented on test/unit/lists-component.spec.ts
> +    it('should resolve', () => {
What if we add here the `with the list` phrase to make the assertion clearer?
```suggestion
    it('should resolve with the list', () => {
```

2023-05-15 19:30 UTC, LautaroPetaccio commented on test/unit/lists-component.spec.ts
> +      it('should resolve', () => {
What if we add here the `with the list` phrase to make the assertion clearer?
```suggestion
      it('should resolve with the list', () => {
```

2023-05-15 19:30 UTC, LautaroPetaccio commented on test/unit/lists-component.spec.ts
> +    it('should resolve', () => {
What if we add here the `with the list` phrase to make the assertion clearer?
```suggestion
    it('should resolve with the list', () => {
```

2023-05-15 19:30 UTC, LautaroPetaccio commented on src/ports/lists/component.ts
> +    { requiredPermissions, considerDefaultList = true, userAddress }: GetListOptions
If we make the `requiredPermissions` an array, the parameters might be a bit confusing in terms of requirements as requiring the EDIT permission always implies that the `VIEW` one must be added as well to the parameter. What if we use it as an enum and check it logically in this method?

2023-05-15 19:30 UTC, LautaroPetaccio commented on src/controllers/handlers/lists-handlers.ts
> +  const listResult = await listsComponent.getList(params.id, { userAddress })
When getting a list here, the required permissions are not being sent, would you mind adding it?

2023-05-16 13:05 UTC, merged