feat: Add Update List endpoint
decentraland/marketplace-favorites-server pull request #126
Opened 2023-05-18 13:02 UTC by kevinszuchet

Closes #114

2023-05-22 20:14 UTC, LautaroPetaccio requested changes
Looks great! ✅  I've left some comments to review, but the code looks awesome.

2023-05-22 20:14 UTC, LautaroPetaccio commented on src/ports/lists/types.ts
> +export type UpdateListRequestBody = Pick<AddListRequestBody, 'name' | 'description'> & {
The name should be optional, right?

2023-05-23 08:32 UTC, kevinszuchet commented on src/controllers/handlers/lists-handlers.ts
> +    } else if (body.name && params.id === DEFAULT_LIST_ID) {
Have we decided we won't let users change the privacy of the default list?

2023-05-23 17:57 UTC, LautaroPetaccio commented on src/controllers/handlers/lists-handlers.ts
> +    } else if (body.name && params.id === DEFAULT_LIST_ID) {
We don't have the code to prevent changing the list description or privacy yet nor the design decision, so I would prevent for the time being and then code what's needed if the design requirement changes.

2023-05-23 19:04 UTC, LautaroPetaccio requested changes

2023-05-23 19:04 UTC, LautaroPetaccio commented on src/ports/lists/component.ts
> +        updateQuery.append(SQL`${column} = ${updatedList[column]}`)
SQL parameters can't be used for columns, only for values. This will produce:
```
 UPDATE favorites.lists SET $1 = $2 WHERE id = $3 AND user_address = $4 RETURNING *
```
which will result in:
```
syntax error at or near "$1" at character 28
```

2023-05-24 09:08 UTC, kevinszuchet commented on package.json
> +    "lodash": "^4.17.21"
I wasn't aware of that. I'll remove the import and consider another solution. Thank you for bringing it to me.

2023-05-24 12:55 UTC, LautaroPetaccio commented on src/ports/lists/component.ts
> +      if (isPrivate) validateAccessExists(id, Permission.VIEW, GRANTED_TO_ALL, accessResult)
It seems that you're performing a commit after the validations are completed. If an exception is thrown, the result would have been already committed and the rollback will be performed as an invalid directive. Would you mind moving the commit below the validations?

2023-05-24 13:05 UTC, LautaroPetaccio approved these changes
Great work! Ship it 🛥️

2023-05-24 13:07 UTC, merged