feat: Sort picks by the logged user
decentraland/marketplace-favorites-server pull request #71
Opened 2023-04-17 14:54 UTC by kevinszuchet

Related to https://github.com/decentraland/marketplace/issues/1567

2023-04-17 15:25 UTC, LautaroPetaccio commented on src/ports/picks/component.ts
> +      query.append(SQL`, (CASE WHEN user_address = ${userAddress} THEN 1 ELSE 0 END)::BOOLEAN AS picked_by_user`)
What do you think about omitting the boolean here as the number will work as well for the order?
```suggestion
      query.append(SQL`, (CASE WHEN user_address = ${userAddress} THEN 1 ELSE 0 END) AS picked_by_user`)
```

2023-04-17 15:27 UTC, LautaroPetaccio commented on src/ports/picks/component.ts
> +      ORDER BY picked_by_user DESC, user_address
What if we change the default ordering from `user_address` to created_at here as well? We would return the listing ordered by its creation date, which seems a bit better:
```suggestion
      ORDER BY picked_by_user DESC, created_at DESC
```

2023-04-17 17:30 UTC, LautaroPetaccio requested changes

2023-04-17 17:30 UTC, LautaroPetaccio commented on src/ports/picks/component.ts
> +        SELECT DISTINCT favorites.picks.user_address, favorites.picks.created_at FROM favorites.picks, favorites.voting
Won't this change return more than one entry for a `user_address`? That is, before, we were getting the unique results for a `user_address`, but with the `created_at` we're going to be getting more than one as the tuple (`favorites.picks.user_address, favorites.picks.created_at`) is the one to check for uniqueness. `SELECT DISTINCT ON` over the `favorites.picks.user_address` column might fix the issue.

2023-04-18 09:16 UTC, kevinszuchet commented on src/ports/picks/component.ts
> +        SELECT DISTINCT favorites.picks.user_address, favorites.picks.created_at FROM favorites.picks, favorites.voting
Great catch! Thanks for the suggestion.

2023-04-18 14:31 UTC, LautaroPetaccio approved these changes
Great change 🚀

2023-04-18 14:46 UTC, merged